export const config = {
  // Dominio público oficial (sin www). www y http redirigen aquí.
  DOMINIO: "dotcasa.com.mx",

  // Constantes de negocio
  TIPOS: new Set([
    "casa",
    "departamento",
    "terreno",
    "rancho",
    "cabana",
    "quinta",
    "oficina",
    "local-comercial",
    "bodega-comercial",
    "nave-industrial",
    "bodega-industrial",
    "edificio",
  ]),
  OPS: new Set(["venta", "renta", "preventa"]),
  ESTADOS: new Set([
    "aguascalientes",
    "baja-california",
    "baja-california-sur",
    "campeche",
    "chiapas",
    "chihuahua",
    "ciudad-de-mexico",
    "coahuila",
    "colima",
    "durango",
    "guanajuato",
    "guerrero",
    "hidalgo",
    "jalisco",
    "estado-de-mexico",
    "michoacan",
    "morelos",
    "nayarit",
    "nuevo-leon",
    "oaxaca",
    "puebla",
    "queretaro",
    "quintana-roo",
    "san-luis-potosi",
    "sinaloa",
    "sonora",
    "tabasco",
    "tamaulipas",
    "tlaxcala",
    "veracruz",
    "yucatan",
    "zacatecas",
  ]),
  CP_REGEX: /^\d{5}$/,

  // Páginas fijas de Bubble que van al sitemap (ruta exacta, tal cual)
  PAGINAS_ESTATICAS: [
    "/propiedades",
    "/acerca_de_nosotros",
    "/terminos_y_condiciones",
    "/politica_de_privacidad",
  ],

  // Configuración de Bubble Data API
  BUBBLE: {
    API_TIPO: "ruta",
    API_CAMPO_SLUG: "slug",
    API_CAMPO_TOTAL: "total_propiedades",
    CACHE_SEGUNDOS: 600,
    SITEMAP_MAX_PAGINAS: 50,
    // Rutas (listados) con menos propiedades que esto no van al sitemap
    SITEMAP_MIN_PROPIEDADES: 2,
    API_TIPO_PROP: "propiedades",
    API_CAMPO_SLUGTEXT: "Slug_text",
  },
};
